### ISSUE TITLE
Transfer to the community?

### ISSUE THREAD

**Issue by majormoses** [sensu-plugins/sensu-plugins-zfs#4]
Hello I am a maintainer of https://github.com/sensu-plugins any chance you might want to open an issue and transfer this over to the community?

If you are interested you can read about the process here: https://github.com/sensu-plugins/community/blob/master/TRANSFERRING_REPOS.md and create an issue here: https://github.com/sensu-plugins/community/issues/new to start the process to transfer it over.

**Comment by blacksails** [comment]
I have very little time maintaining the plugin, so it would be very nice to have it transfered to the community. I have opened an issue to initiate the transfer.
